dofile(os.getenv("HOME") .. "/.config/conky/colors.lua")

conky.config = {
    background = true, 
    border_width = 2,
    out_to_x = false,
    out_to_wayland = true,
    cpu_avg_samples = 2,
    default_color = "white",
    double_buffer = true,
    draw_borders = false,
    draw_graph_borders = false,
    draw_outline = false,
    draw_shades = false,
    extra_newline = false,
    font = 'Fira Code:size=14',
    net_avg_samples = 2,
    no_buffers = true,
    out_to_console = false,
    out_to_ncurses = false,
    out_to_stderr = false,
    own_window = true,
    own_window_class = 'Conky',
    own_window_type = 'desktop',
    own_window_colour = 'black',
    show_graph_range = false,
    show_graph_scale = true,
    stippled_borders = 0,
    update_interval = 1.0,
    uppercase = false,
    use_spacer = 'none',
    use_xft = true,
    color0 = color3,
    own_window_argb_visual = true,
    own_window_argb_value = 0,
    own_window_hints = 'undecorated,sticky,skip_taskbar,skip_pager,below'
}
